"""
Localization helpers for Farm Monitor.

This module keeps all user-visible strings in one place so UI/API/PDF can share them.
Supported languages:
- en: English
- hi: Hindi
- gu: Gujarati
"""

from __future__ import annotations

from typing import Any, Dict

SUPPORTED_LANGS = {"en", "hi", "gu"}
DEFAULT_LANG = "en"


def normalize_lang(lang: str | None) -> str:
    if not isinstance(lang, str):
        return DEFAULT_LANG
    lang = lang.strip().lower()
    return lang if lang in SUPPORTED_LANGS else DEFAULT_LANG


STRINGS: Dict[str, Dict[str, str]] = {
    "en": {
        # PDF / general labels
        "pdf_title": "Farm Monitoring Report",
        "farm_name": "Farm Name:",
        "crop_type": "Crop Type:",
        "field_area": "Field Area:",
        "location": "Location:",
        "report_date": "Report Date:",
        "executive_summary": "Executive Summary",
        "crop_health_status": "Crop Health Status:",
        "growth_stage": "Growth Stage:",
        "vegetation_index": "Vegetation Index (NDVI):",
        "satellite_analysis": "Satellite Analysis",
        "weather_analysis": "Weather Analysis",
        "agronomic_recommendations": "Agronomic Recommendations",
        "risk_assessment": "Risk Assessment",
        "metric": "Metric",
        "value": "Value",
        "interpretation": "Interpretation",
        "status": "Status",
        "risk_category": "Risk Category",
        "level": "Level",
        "drought_risk": "Drought Risk",
        "flood_risk": "Flood Risk",
        "disease_risk": "Disease Risk",
        "heat_stress_risk": "Heat Stress Risk",
        "overall_risk": "Overall Risk",
        "image_quality": "Image quality",
        "field_variability": "Field variability",
        "expected_precip": "Expected precipitation",
        "compared_prev_period": "Compared to previous period",
        "automated_disclaimer": "This is an automated analysis. Always verify recommendations with local agronomists.",
        "data_sources": "Data Sources: Sentinel-2 (ESA) • Open-Meteo • OpenStreetMap",
        "generated_by": "This report was generated by Farm Monitor - A Zero-Cost Farm Monitoring System",
    },
    "hi": {
        "pdf_title": "खेत निगरानी रिपोर्ट",
        "farm_name": "खेत का नाम:",
        "crop_type": "फसल का प्रकार:",
        "field_area": "खेत का क्षेत्रफल:",
        "location": "स्थान:",
        "report_date": "रिपोर्ट तिथि:",
        "executive_summary": "कार्यकारी सारांश",
        "crop_health_status": "फसल स्वास्थ्य स्थिति:",
        "growth_stage": "वृद्धि अवस्था:",
        "vegetation_index": "वनस्पति सूचकांक (NDVI):",
        "satellite_analysis": "उपग्रह विश्लेषण",
        "weather_analysis": "मौसम विश्लेषण",
        "agronomic_recommendations": "कृषि सिफ़ारिशें",
        "risk_assessment": "जोखिम आकलन",
        "metric": "मापदंड",
        "value": "मान",
        "interpretation": "व्याख्या",
        "status": "स्थिति",
        "risk_category": "जोखिम श्रेणी",
        "level": "स्तर",
        "drought_risk": "सूखा जोखिम",
        "flood_risk": "बाढ़ जोखिम",
        "disease_risk": "रोग जोखिम",
        "heat_stress_risk": "गर्मी तनाव जोखिम",
        "overall_risk": "कुल जोखिम",
        "image_quality": "छवि गुणवत्ता",
        "field_variability": "खेत में भिन्नता",
        "expected_precip": "अपेक्षित वर्षा",
        "compared_prev_period": "पिछली अवधि की तुलना में",
        "automated_disclaimer": "यह एक स्वचालित विश्लेषण है। स्थानीय कृषि विशेषज्ञों से सत्यापन करें।",
        "data_sources": "डेटा स्रोत: Sentinel-2 (ESA) • Open-Meteo • OpenStreetMap",
        "generated_by": "यह रिपोर्ट Farm Monitor द्वारा बनाई गई है - एक शून्य-लागत खेत निगरानी प्रणाली",
    },
    "gu": {
        "pdf_title": "ખેતર નિરીક્ષણ રિપોર્ટ",
        "farm_name": "ખેતરનું નામ:",
        "crop_type": "પાકનો પ્રકાર:",
        "field_area": "ખેતરનું ક્ષેત્રફળ:",
        "location": "સ્થાન:",
        "report_date": "રિપોર્ટ તારીખ:",
        "executive_summary": "કાર્યકારી સારાંશ",
        "crop_health_status": "પાકની આરોગ્ય સ્થિતિ:",
        "growth_stage": "વૃદ્ધિ સ્થિતિ:",
        "vegetation_index": "વનસ્પતિ સૂચકાંક (NDVI):",
        "satellite_analysis": "ઉપગ્રહ વિશ્લેષણ",
        "weather_analysis": "હવામાન વિશ્લેષણ",
        "agronomic_recommendations": "કૃષિ ભલામણો",
        "risk_assessment": "જોખમ મૂલ્યાંકન",
        "metric": "મેટ્રિક",
        "value": "મૂલ્ય",
        "interpretation": "અર્થઘટન",
        "status": "સ્થિતિ",
        "risk_category": "જોખમ શ્રેણી",
        "level": "સ્તર",
        "drought_risk": "સૂકા જોખમ",
        "flood_risk": "પૂર જોખમ",
        "disease_risk": "રોગ જોખમ",
        "heat_stress_risk": "ઉષ્ણતા તાણ જોખમ",
        "overall_risk": "કુલ જોખમ",
        "image_quality": "છબી ગુણવત્તા",
        "field_variability": "ખેતરમાં ફેરફાર",
        "expected_precip": "અપેક્ષિત વરસાદ",
        "compared_prev_period": "પાછલા સમયગાળા સાથે તુલના",
        "automated_disclaimer": "આ સ્વચાલિત વિશ્લેષણ છે. સ્થાનિક કૃષિ નિષ્ણાતો સાથે ભલામણો ચકાસો.",
        "data_sources": "ડેટા સ્ત્રોત: Sentinel-2 (ESA) • Open-Meteo • OpenStreetMap",
        "generated_by": "આ રિપોર્ટ Farm Monitor દ્વારા બનાવાયો છે - શૂન્ય ખર્ચની ખેતર નિરીક્ષણ સિસ્ટમ",
    },
}


def t(lang: str | None, key: str, **kwargs: Any) -> str:
    lang_n = normalize_lang(lang)
    table = STRINGS.get(lang_n, STRINGS[DEFAULT_LANG])
    base = table.get(key) or STRINGS[DEFAULT_LANG].get(key) or key
    if not kwargs:
        return base
    try:
        return base.format(**kwargs)
    except Exception:
        return base


HEALTH_STATUS = {
    "en": {
        "Excellent": "Excellent",
        "Good": "Good",
        "Moderate": "Moderate",
        "Poor": "Poor",
        "Critical": "Critical",
    },
    "hi": {
        "Excellent": "उत्कृष्ट",
        "Good": "अच्छा",
        "Moderate": "मध्यम",
        "Poor": "खराब",
        "Critical": "गंभीर",
    },
    "gu": {
        "Excellent": "ઉત્તમ",
        "Good": "સારું",
        "Moderate": "મધ્યમ",
        "Poor": "ખરાબ",
        "Critical": "ગંભીર",
    },
}


GROWTH_STAGE = {
    "en": {
        "Unknown": "Unknown",
        "Not Planted": "Not Planted",
        "Early Growth": "Early Growth",
        "Vegetative": "Vegetative",
        "Flowering": "Flowering",
        "Fruiting/Grain Fill": "Fruiting/Grain Fill",
        "Maturity/Harvest": "Maturity/Harvest",
    },
    "hi": {
        "Unknown": "अज्ञात",
        "Not Planted": "अभी नहीं बोया गया",
        "Early Growth": "प्रारंभिक वृद्धि",
        "Vegetative": "वनस्पतिक",
        "Flowering": "फूलना",
        "Fruiting/Grain Fill": "फल/दाना भरना",
        "Maturity/Harvest": "परिपक्वता/कटाई",
    },
    "gu": {
        "Unknown": "અજ્ઞાત",
        "Not Planted": "હજુ વાવ્યું નથી",
        "Early Growth": "પ્રારંભિક વૃદ્ધિ",
        "Vegetative": "વનસ્પતિ અવસ્થા",
        "Flowering": "ફૂલાવસ્થા",
        "Fruiting/Grain Fill": "ફળ/દાણા ભરાવ",
        "Maturity/Harvest": "પરિપક્વતા/કાપણી",
    },
}


def translate_health_status(lang: str | None, status: str) -> str:
    lang_n = normalize_lang(lang)
    table = HEALTH_STATUS.get(lang_n, HEALTH_STATUS["en"])
    return table.get(status, status)


def translate_growth_stage(lang: str | None, stage: str) -> str:
    lang_n = normalize_lang(lang)
    table = GROWTH_STAGE.get(lang_n, GROWTH_STAGE["en"])
    return table.get(stage, stage)

